product_view:
    path: /product/{product_id}
    controller: App\Controller\ProductController::getProduct
    methods:
        - GET

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
